### PR TITLE
Pr 2897

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov it seems https://ci.eclipse.org/tycho/job/tycho-github/job/PR-2903/1/testReport/junit/org.eclipse.tycho.test.surefire/JUnit5Test/testJUnit5Runner/ is using a very old eclipse still the test explicitly seem to reference an oxygen target but I'm not sure what it actually testing that it requires such old eclipse?

**Comment by laeubi** [comment]
@akurtakov it seems https://ci.eclipse.org/tycho/job/tycho-github/job/PR-2903/1/testReport/junit/org.eclipse.tycho.test.eeProfile/CustomProfileIntegrationTest/testBuildWithCustomProfile/ is also suffering from now `java.*` imports not resolvable ... do you have an idea how to upgrade that test?

**Comment by laeubi** [comment]
@akurtakov https://ci.eclipse.org/tycho/job/tycho-github/job/PR-2903/1/testReport/junit/org.eclipse.tycho.test.TYCHO0367localRepositoryCrosstalk/LocalRepositoryCrosstalkTest/test/ seems another candidate that uses way too old OSGi framework...

**Comment by akurtakov** [comment]
No idea. Many tests just used hardcoded versions at the time they were created. In the last few years, I've been updating them (when noticed) to use the latest version where possible. This is quite time consuming.

**Comment by laeubi** [comment]
Would you mind checking if we can update those test? I think this is independent from BND update but currently blocks the update.

**Comment by akurtakov** [comment]
I'll try  to find time for it.

**Comment by akurtakov** [comment]
The two left will require more time than I can spend on it for now. The two remaining tests will probably need bigger changes.

**Comment by laeubi** [comment]
Thanks at least we solved the obvious now I'm currently have no clue why the others are failing needs probably a debug session again...

**Comment by laeubi** [comment]
@akurtakov I think I was able to "fix" the `LocalRepositoryCrosstalkTest` now ...

**Comment by laeubi** [comment]
Hopefully `CustomProfileIntegrationTest` is fixed now as well...

**Comment by laeubi** [comment]
Build is green but we have outstanding license issues...

**Comment by akurtakov** [comment]
Jenkins succeeded and licensecheck is fine. Merging.

**Pull request merged**
