### PR TITLE
Issue 309 Add Integration test for updating pom version

### PR DESCRIPTION
**Pull request by DieterMai**
Added 2 tests to verify the update of the pom version to the manifest version.

testUpdatePomOfPomThatIsNamedPomXml()
- This test verifies the behavior for poms named 'pom.xml'

testUpdatePomOfPomThatIsNotNamedPomXml()
- This test verifies the behavior for poms that are not called 'pom.xml'

- Fixed some errors in CONTRIBUTING.md

### CODE REVIEW

**Comment by laeubi** [comment]
@DieterMai do you plan to propose a fix for this?

**Comment by laeubi** [comment]
@DieterMai can you resolve the conflicts, and rebase on top of current master?

**Comment by DieterMai** [comment]
Hi @laeubi . Its a long time since i worked on this. As far as i remember the last state was that the update version plugin failed to do its job except for the most simple use cases. My fix only fixed some of that.

The issues with the update version plugin exist since it was written. Yet nobody besides me seem to complain. Do you know if this plugin is actually used? Because if not, I'm am not motivated to invest time. If it is used and a fix for its issues appreciated by the community, I'm happy to continue.

**Comment by laeubi** [comment]
@DieterMai it is an official plugin and I at least know some projects using it (include eclipse-platform), sadly the test-coverage is quite low, so every test-case (and of course fixes) are of course welcome.

**Pull request closed without merging**
