### PR TITLE
Use some instanceof patterns

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by laeubi** [comment]
@mickaelistria can we hold back such changes until 3.0.0 release (Fr next week) to get smaller change sets in case of regression fixes?

**Comment by mickaelistria** [comment]
Sure, I mostly submitted it to see how CI likes it; it's not meant for 3.0 at all.

**Comment by laeubi** [comment]
@mickaelistria as no one has reported major regression until now I think its fine to merge these when the test/ci is fine ...

**Comment by mickaelistria** [comment]
Merged as part of #1425

**Pull request closed without merging**
