### PR TITLE
Fix the base path for the setup's clone location

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov I missed this one during the previous round of URI fixes.

**Review by laeubi — APPROVED** [review]

**Comment by laeubi** [comment]
We don't need to wait for the build here I think...

**Comment by merks** [comment]
@laeubi Thanks.  Indeed this obviously has no impact on the build.  I often cancel such builds for the sake of climate change...

**Comment by laeubi** [comment]
Actually one can even configure what files should trigger builds, but I didn't get to this from my long backlog yet :-\

**Comment by akurtakov** [comment]
That's how alive project looks and works - by the time you end up seeing someone - someone already acted on and it's merged :) . "Given enough eyeballs, all bugs are shallow"

**Pull request merged**
