### PR TITLE
Adjust Oomph setup for master->main branch change

### PR DESCRIPTION
**Pull request by HeikoKlare**

### CODE REVIEW

**Comment by HeikoKlare** [comment]
I've successfully tested the updated setup locally.

**Comment by laeubi** [comment]
Maybe @merks can review as well.

**Comment by merks** [comment]
That looks correct if you are renaming the master branch to main.

**Comment by akurtakov** [comment]
It already happened thus merging.

**Comment by HannesWell** [comment]
Looks good.
I just wanted to mention that due to the change in the stream name one has to fix existing workspace setups, i.e. the previously referenced stream does not exist anymore and has to be changed to the main stream.
Not ideal, but better do it now than to keep it inconsistent.

For the record to fix
grafik
one has to delete the broken stream reference and just drag-and-drop the new one from the setup in the workspace.
In the end the first line should be replaced by the second line.
```
<stream href="index:/org.eclipse.setup#//@projectCatalogs[name='org.eclipse']/@projects[name='tycho']/@streams[name='master']"/>
  <stream href="index:/org.eclipse.setup#//@projectCatalogs[name='org.eclipse']/@projects[name='tycho']/@streams[name='main']"/>
```

**Comment by HeikoKlare** [comment]
Thanks for the hint, Hannes! I did not think about that and did not face the problem, as I had not preexisting setup. Sorry for this inconvience. But as you mentioned, it is probably best to have this rename done consistently.

**Pull request merged**
