### PR TITLE
Provide tycho-surefire integration test for JUnit 5 suites

### PR DESCRIPTION
**Pull request by HeikoKlare**
This is an initial draft for an integration test for using JUnit 5 suites in tycho-surefire.
It is supposed to demonstrate the behavior discussed in 
- #2462

### CODE REVIEW

**Comment by laeubi** [comment]
@HeikoKlare the referenced issue seems odd, do you maybe want to reference another issue or an issue in a different repository?

**Comment by HeikoKlare** [comment]
> the referenced issue seems odd, do you maybe want to reference another issue or an issue in a different repository?

Thanks! Yes, sorry for that. I corrected the referenced issue.

**Comment by HeikoKlare** [comment]
To ease investigation of the issue, here is the same test setup with pure Maven surefire: [bundle.test.zip](https://github.com/eclipse-tycho/tycho/files/13888591/bundle.test.zip)
That configuration works fine with test suite as long `junit-platform-suite-engine` is on the classpath.

**Comment by laeubi** [comment]
@HeikoKlare 

is this supposed to fix the mentioned issue:
- https://github.com/eclipse-tycho/tycho/pull/3358

**Comment by HeikoKlare** [comment]
The test case provided here was only supposed to demonstrate the issue documented in:
- #2462

The test case is also integrated into and thus subsumed by the PR supposed to fix the issue:
- #3358

So in case #3358 gets merged, this becomes obsolete.

**Pull request closed without merging**
