### PR TITLE
Reproducer for packaging issue 1621

### PR DESCRIPTION
**Pull request by lppedd**
This is targeting 2.7.5 as in my working environment I can't currently update to 3.0.0 and Java 17.
Feel free to modify the code as needed.

See issue #1621.

### CODE REVIEW

**Comment by lppedd** [comment]
I have actually updated my Eclipse contributor agreement. Not sure what I'm missing.

image

**Comment by laeubi** [comment]
@lppedd you need to make sure you use the same e-mailadress and you need to add your girhub username to the eclipse profile (under "social links" section). Then it usually takes a few hours for EclipseECA tool do sync that data.

**Comment by lppedd** [comment]
@laeubi I had already set everything to the correct values. Let's wait I suppose.
If you need something changed in the PR just let me know.

**Comment by lppedd** [comment]
Now the ECA is ok. Thanks for the tips!

**Pull request closed without merging**
