### PR TITLE
Add support for generation of OSGi repository format

### PR DESCRIPTION
**Pull request by laeubi**
OSGi specifies a standardized repository format [1] to provide bundles and other resources. This adds support for generating such standardized format out of the content of the P2 repository alongside with the p2 format to improve interoperability of tools.

[1] https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.repository.html

Fix https://github.com/eclipse-tycho/tycho/issues/34

### CODE REVIEW

**Comment by mickaelistria** [comment]
Cool! So this feature is enabled by default for eclipse-repository packaging type?

**Comment by laeubi** [comment]
It is disabled by default, you can see here how to enable it:

https://github.com/eclipse-tycho/tycho/blob/master/RELEASE_NOTES.md#building-osgi-repositories-with-tycho-p2-repository-pluginassemble-repository

My plan would be to enable it for the i-builds (if possible) so we have a larger repository for investigation/testing, ideally it would also be enabled for the eclispe releases but I have no idea if the release repos are actually build by Tycho...

**Comment by mickaelistria** [comment]
> It is disabled by default

Why not turning it on by default? Does it has a major impact on performance?

> My plan would be to enable it for the i-builds (if possible) so we have a larger repository for investigation/testing, ideally it would also be enabled for the eclispe releases but I have no idea if the release repos are actually build by Tycho...

You can try twaeking https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/pom.xml

**Comment by laeubi** [comment]
> Why not turning it on by default? Does it has a major impact on performance?

I found that there is always anyone unhappy with that and i haven't measured the performance yet but for lager sides it might add a few seconds as this currently needs to read all bundle/feature jars and analyze them then serialize back to XML ...

**Comment by mickaelistria** [comment]
> I found that there is always anyone unhappy

Keeping everyone happy is an impossible requirement; sometimes people are unhappy for no good reason.

**Comment by laeubi** [comment]
Since its a major release it would be fine to make it the default, we then should just add a note to the migration guide how to disable the feature, so if you like just open a PR that makes it enabled by default :-)

**Pull request merged**
