### PR TITLE
Update latest release to 2024-03

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by laeubi** [comment]
FYI @akurtakov

**Comment by akurtakov** [comment]
Do you ask me to look into it?

**Comment by laeubi** [comment]
If you have time it would be great!

**Comment by akurtakov** [comment]
I have opened amended PR https://github.com/eclipse-tycho/tycho/pull/3677 that should hopefully finish this one.

**Comment by akurtakov** [comment]
Fixed via the alternative PR.

**Pull request closed without merging**
