### PR TITLE
Switch maven-compat to maven-core in tycho-source-plugin

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
This was the last compat runtime dependency I have found.

**Comment by laeubi** [comment]
Thanks! Now I think we need only get rid of the old MavenResolver and use Aether instead directly I'll try to take a look the next days...

**Comment by akurtakov** [comment]
What about jsr330 migration?

**Comment by laeubi** [comment]
> What about jsr330 migration?

This would strictly require Maven 3.9.x (because 3.8.x uses old injector that do not support Java 17) and beside that it is "more modern" I think we don't have any benefit (yet) from using it.

**Pull request merged**
