### PR TITLE
Improve FTP reconnection logic

### LINKED ISSUE #2054: FTP connection should be kept alive/re-initialized during build process
If a lot of time might pass by between FTP calls, the FTP connection might be dropped abruptly.  
A good enhancement might be using a background thread sending `NOOP` commands to keep the connection alive, or re-connect automatically when a `FTPConnectionClosedException` is thrown.

### PR DESCRIPTION
**Pull request by lppedd**
Very small change that makes reconnection actually work when needed.  
The client, besides verifying if the socket connection is open, tries to send a NOOP command.
Both checks must succeed, otherwise a new connection is created.

Closes #2054

Note: @laeubi in debug I see two instances of `FtpTransportProtocolHandler` gets created, any idea how's that possible?

### CODE REVIEW

**Comment by laeubi** [comment]
> Note: @laeubi in debug I see two instances of FtpTransportProtocolHandler gets created, any idea how's that possible?

Maven uses different classlaoders (realms) so components are maybe created multiple times depending on the realm they live in ...

**Comment by lppedd** [comment]
@laeubi oh, that sounds ok. Tho, should the `clients` map be static then? 
I don't like static stuff but if it avoids created unnecessary connections...

```java
/**
* FTP clients with an open connection.
* Every client should be disposed at the end of the build.
*/
private final Map<String, FTPClient> clients = new ConcurrentHashMap<>(8);
```

**Comment by laeubi** [comment]
> @laeubi oh, that sounds ok. Tho, should the `clients` map be static then? I don't like static stuff but if it avoids creating unnecessary connections...
> 
> ```java
> /**
> * FTP clients with an open connection.
> * Every client should be disposed at the end of the build.
> */
> private final Map<String, FTPClient> clients = new ConcurrentHashMap<>(8);
> ```

That won't work, as different classlaoders will result in different classes that have different statics, I think we have to live with that for now.

**Comment by laeubi** [comment]
Well if it helps anything, a static might be fine here.

**Comment by laeubi** [comment]
ECA checks are currently broken ... see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2636

**Pull request merged**
