### PR TITLE
[backport] Include (but not enable) the smartbuilder build-extension

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by akurtakov** [comment]
From IP POV until https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/7206 is approved you can't do 3.0.x release with this patch in.

**Comment by laeubi** [comment]
> From IP POV until https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/7206 is approved you can't do 3.0.x release with this patch in. It's fine to merge it in the codebase while pending IP team response.

I hope this is resolved soon, strange enough this dripped in with another update that seems has passed the validation already... I might just revert this if its to complicated as its nothing we *ship* it is just a plugin used to *build* ...

**Comment by akurtakov** [comment]
It must come as a runtime dependency of some module.

**Comment by laeubi** [comment]
It contains the `@Mojo` annotations and alike, so yes it is a (provided) dependency but will come from the maven distribution ...

**Comment by akurtakov** [comment]
This probably means that https://github.com/eclipse/dash-licenses is not filtering out provided dependencies.

**Comment by laeubi** [comment]
> This probably means that https://github.com/eclipse/dash-licenses is not filtering out provided dependencies.

I don't know if its a bug or intentionally, but that's possible, at least I have only found provided references in the Tycho code.

**Pull request merged**
