### PR TITLE
Update to 2024-06 release

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by akurtakov** [comment]
@dependabot rebase

**Comment by akurtakov** [comment]
@dependabot rebase

**Comment by sratz** [comment]
What's the reason for closing this and not moving to Eclipse 2024-06 for Tycho 4.0.x?

**Comment by laeubi** [comment]
Most updates are done but some require higher attention. As these are not important for Tycho 4 I decided to skipp them (as the next release is already around the corner).

**Pull request closed without merging**
