### PR TITLE
Skip resolving if no mojo requires dependency resolution

### PR DESCRIPTION
**Pull request by laeubi**
This skips resolving of the project if no mojo requires actual dependency resolution.

### CODE REVIEW

**Comment by lppedd** [comment]
Hi @laeubi. Just noticed this PR. Curious to understand if it could affect - in a good way - this topic https://github.com/eclipse-tycho/tycho/discussions/1304

**Comment by laeubi** [comment]
@lppedd You can try that out by specify `-Dtycho.resolver.classic=false` but be aware that 

> I have a plugin goal bound to the initialize phase, which goes through dependencies and copy some files using the Dependencies Plugin.

mostly indicates that you *are* actually requiring dependency resolution so if it would change something in your workflow depends on different aspects and your error more indicates that your local repository do not contain the required SNAPSHOT files (and as you are not running through the package phase they are not generated).

**Comment by lppedd** [comment]
@laeubi Thanks! And yes, I need dependencies, but not p2 ones, so not resolved by Tycho, only standard Maven dependencies.
I don't know if it's possible to differentiate the two.

**Comment by lppedd** [comment]
@laeubi I've tried with today snapshot, `-Dtycho.resolver.classic=false`, and a dumb `generate-sources` goal.
Still the same problem. Is it ok if I try to send a reproducer?

**Comment by laeubi** [comment]
@lppedd [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue are always welcome, I'm just not sure if we can do much, because it does not matter how "dumb" a phase it, but if it has mojos that require dependency resolution.

**Pull request merged**
