### PR TITLE
Minor simplifications and clean-ups in Toolchain processing

### PR DESCRIPTION
**Pull request by HannesWell**
Replace deprecated DefaultJavaToolChain by JavaToolchainImpl.

Initially part of https://github.com/eclipse-tycho/tycho/pull/2379, but there seem to be some bugs in this change.
@laeubi do you directly have any hot hint?

### CODE REVIEW

**Comment by laeubi** [comment]
@HannesWell I have no immediate idea, especially as these are maven classes, you cna try to even split this more into some simplifications that are maybe less critical, beside that, in the past it has worked well to abstract the maven parts (e.g by doing as much as possible in tycho-core) instead of any of the mojos,, I even using reflection on some places :-\

**Comment by laeubi** [comment]
@HannesWell do you plan to work on this or should we postpone this until Maven 4?

**Comment by HannesWell** [comment]
I temporarily reverted the replacement of the deprecated DefaultJavaToolChain. Lets see if this makes a difference. I also checked again the other changes and actually they look save, but I might have overseen something.

**Comment by HannesWell** [comment]
> I temporarily reverted the replacement of the deprecated DefaultJavaToolChain. Lets see if this makes a difference. I also checked again the other changes and actually they look save, but I might have overseen something.

OK, that worked. But I don't understand why it breaks something if we just use the super-class.
Lets try it again and the previous failure was just a temporary issue.
If it still fails, lets submit this with the deprecated `DefaultJavaToolChain` in place.

**Comment by HannesWell** [comment]
Looks like this worked now.
Could it be that the test-runners where using a too old Maven version?
Any way, @laeubi any object to merge this now?

**Comment by laeubi** [comment]
> Could it be that the test-runners where using a too old Maven version?

I have no clue, as it works now I don't see a reason to further wait with this.

**Pull request merged**
