### PR TITLE
Fix Java warnings

### PR DESCRIPTION
**Pull request by HannesWell**
The main question is if the called P2 applications can handle correctly created URL via `File.toURI().toURL()`?

### CODE REVIEW

**Comment by HannesWell** [comment]
@laeubi is it save to remove those unused properties or are they again used somewhere reflectively?

**Comment by HannesWell** [comment]
@laeubi can I ignore the failure of `LocalRepositoryCrosstalkTest`? Locally it works on my Windows computer.

**Comment by laeubi** [comment]
I hope I have fixed that random failure so if you rebase it should hopefully be fine....

**Comment by laeubi** [comment]
@HannesWell I have no idea why this happens (again) now it seems sometimes the m2 repo gets wrecked :-(

**Comment by HannesWell** [comment]
> @HannesWell I have no idea why this happens (again) now it seems sometimes the m2 repo gets wrecked :-(

Hmm. Lets see, maybe we are lucky and a rebase makes it work (or it was just a random failure).

**Comment by HannesWell** [comment]
> > @HannesWell I have no idea why this happens (again) now it seems sometimes the m2 repo gets wrecked :-(
> 
> Hmm. Lets see, maybe we are lucky and a rebase makes it work (or it was just a random failure).

Looks like this worked. Submitting it.

**Pull request merged**
