### PR TITLE
Add Custom URL for generic Eclipse sponsoring

### PR DESCRIPTION
**Pull request by laeubi**
@mickaelistria WDYT?

As  https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/963 is stuck, would you mind to bring this to the [Committer Board Representatives](https://www.eclipse.org/org/foundation/directors.php) of Red Hat?

### CODE REVIEW

**Comment by akurtakov** [comment]
I think we can also ask @merks as Committer representative to bring it up.

**Comment by merks** [comment]
There are ongoing discussions at the IDE WG Steering committee about this topic and it will be a topic at the next meeting Sept. 20th.  I'm not sure everyone will be thrilled with how this resolves. The flow of money is seen as something that must be properly managed...

You can look at this site to see the first "pilot project" approach that is under consideration for additional projects:

https://github.com/adoptium
https://github.com/sponsors/adoptium

You should note that there has been little traction...

**Comment by mickaelistria** [comment]
You can add yourself as well, I don't think the discussion on https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/963 forbids us from listing individual committer members in FUNDING.yml so far.

**Comment by mickaelistria** [comment]
@merks This "it's hard to manage" argument doesn't stand here, because this issue is about allowing a way to have things *not managed*. Here we're not asking about sponsoring a project (which would require management), but allowing project to better promote sponsoring of individual committers (who are Eclipse Foundation members) by individual GitHub users. No management is necessary, it's pure peer-to-peer, dis-centralized. It's really a low-hanging fruit of ecosystem development, even it it's only for a few more bucks per months for a few individual, it's still nice while blocking it is not.

**Comment by akurtakov** [comment]
FWIW, I would rather sponsor a person that does some specific work I care about rather than some entity where responsibility will be less clear (if known at all!).

**Comment by merks** [comment]
If you follow all the links you'll noticed you can sponsor George Adams directly and personally:

https://github.com/sponsors/gdams

Links to such a page sis what you want right?

**Comment by akurtakov** [comment]
> If you follow all the links you'll noticed you can sponsor George Adams directly and personally:

He seems to be listed there because he sponsors Adoptium, not because he works on Adoptium and one can decide to sponsor him personally.

**Comment by mickaelistria** [comment]
Yes, that's the kind of links we want.
Basically we want admins to enable sponsoring button for the repository, so then it would show the "sponsoring" block on the right, like you can see on my fork: https://github.com/mickaelistria/tycho .

**Comment by merks** [comment]
> > If you follow all the links you'll noticed you can sponsor George Adams directly and personally:
> 
> He seems to be listed there because he sponsors Adoptium, not because he works on Adoptium and one can decide to sponsor him personally.

He does work on Adoptium:

https://projects.eclipse.org/projects/adoptium.temurin/who

And yes, I assume he's listed because he sponsored Adoptium with at least a $1...

**Comment by merks** [comment]
> Yes, that's the kind of links we want. Basically we want admins to enable sponsoring button for the repository, so then it would show the "sponsoring" block on the right, like you can see on my fork: https://github.com/mickaelistria/tycho .

Unfortunately I think someone will maybe split hairs---please don't shoot the messenger---and argue that sponsoring the project is not the same as sponsoring some individual who is under no obligation to use that money to work on the project being sponsored.  I'm not sure @jonahgraham opinions about these things but his opinions have influence on the decisions of the WG (whereas I have no vote there).

**Comment by akurtakov** [comment]
I don't understand why the IDE WG has a say over that? Tycho is not part of IDE WG nor has ever seen any support from the WG and most likely never will.

**Comment by laeubi** [comment]
> The flow of money is seen as something that must be properly managed...

If there is any money left after "managing" it, why not :-)

One just should not expect that much money it to make here (at the beginning) as stated in the linked issue it is more a way to make it **more visible** that there **are** ways to contribute/push things forward beyond reporting bugs, coding yourself, or hope that more complains make things faster :-)

> hat sponsoring the project is not the same as sponsoring some individual who is under no obligation to use that money to work on the project being sponsored.

I have no clue what EF do with all the sponsoring of Eclipse friends either? Are they oblique to give me direct feedback what they did with the 35 $ I might spend them?

I think the key-point is, that the individual *risk* that the person do not "use it fro the project" is negligible... but it is more to do something "good" ...

> whereas I have no vote there

That's why I said it *might* be good to get support for your voice from a "strategic member" like Red Hat as a representative, but I just don't know if this is even valid or how all that organization stuff works in details :-)

**Comment by mickaelistria** [comment]
Maybe it's just a good time to start planning a fork of Tycho where the project would be finally able to help some of its contributors to get a bit more money easily.
Technically it doesn't seem so hard, I think the only difficulty is just to find another place where to put snapshots, but CI on GitHub is good enough and we already deploy releases to oss.sonatype.org so not much would change.

**Comment by laeubi** [comment]
> I don't understand why the IDE WG has a say over that? Tycho is not part of IDE WG nor has ever seen any support from the WG and most likely never will.

If we would just get 0.01 $ / build to fund Tycho development ... :-)

But as noted, I'm more after *visibility* than making big money...

**Comment by akurtakov** [comment]
> Maybe it's just a good time to start planning a fork of Tycho where the project would be finally able to help some of its contributors to get a bit more money easily. Technically it doesn't seem so hard, I think the only difficulty is just to find another place where to put snapshots, but CI on GitHub is good enough and we already deploy releases to oss.sonatype.org so not much would change.

If entity like IDE WG suddenly gains control over the project actions and decides on the rules rather than the project behaves under the rules coming from EF there might not be other option.

**Comment by laeubi** [comment]
> I think the only difficulty is just to find another place where to put snapshots

Github also offers such thinks for their projects, limited transfer bandwidth unless you pay, but might be enough
https://github.com/features/packages

> But CI on GitHub is good enough 

Sure there are only very slight differences today

> and we already deploy releases to oss.sonatype.org so not much would change.

One need to use a new group id then, but you can even get a group ID based on github org-name, I recently did registered a new group id and it was rather easy :-)

**Comment by merks** [comment]
> I don't understand why the IDE WG has a say over that? Tycho is not part of IDE WG nor has ever seen any support from the WG and most likely never will.

The WG does **not** have a say over that.  The WG is just trying to help and I'm just trying to help.  Clearly Tycho is an integral part of delivering SimRel and while it might not be in Wayne's list because it doesn't deliver content to SimRel repo, it is in my list and I'm trying to ensure that it's in the WG's list such that Tycho will see support from the WG.  E.g., I include these in the simrel.aggran:

image

Note too that neither the WG nor I make any of the rules, the **Foundation makes the rules** and we are all bound by them.  Also note that you folks aren't the only ones who are frustrated.  It feels like a full time job just to respond to the stream of emails, but I try my best to remain constructive and positive.  Unfortunately it feels like much of what I say tends to be bounced back and turned into something negative.  That reduces my motivation to help.  I don't have a magic wand to bend the Foundation to my will.

**Comment by laeubi** [comment]
> Unfortunately it feels like much of what I say tends to be bounced back and turned into something negative. That reduces my motivation to help

@merks I just wanted to say that I always find it helpful and probably just take it sometimes not *too* serious, and some joking will be always there :-)

For me discussing and taking different sights is the most important part, even though it can become very stressful, one might even get the impression that not worth the effort, but in the end I would thin if one get _no feedback at all_ that would be much more an issue.

**Comment by akurtakov** [comment]
@merks I appreciate your efforts here and my reaction is more of a general disappointment and not an effort to shoot the messenger. So effectively the WG is trying to provide suggestions for rules (which IMHO should be a per project decision) because no one else stepped up to do so till now?

**Comment by mickaelistria** [comment]
> Note too that neither the WG nor I make any of the rules, the Foundation makes the rules and we are all bound by them

So there is a rule against our will to have project page listing some possible committers to sponsor? Where can we such rule explicitly? Was is discussed in some Board meeting? Which meeting minutes should we read to learn more about that?
What bugs me the most is that so far, we've not gotten any argument *against* doing that from anyone at EMO; we've just got it enabled, and then disabled without a clear reason and then silence despite numerous pings. And without a clear reason for EF to disable it, then it leaves room for the worst interpretations about EF priorities.

**Comment by merks** [comment]
> @merks I appreciate your efforts here and my reaction is more of a general disappointment and not an effort to shoot the messenger. So effectively the WG is trying to provide suggestions for rules (which IMHO should be a per project decision unless legal concerns) because no one else stepped up to do so till now?

I would characterize it this way.   The Foundation made rules and started a pilot program that you see for Adoptium; I have no knowledge of the detailed discussions and history behind how that came about nor any tradeoffs considered.   When I brought the issue raised by @mickaelistria to the WG, the Foundation proposed extending this pilot program to the IDE WG, with slides to detail the proposal.  That is still currently under discussion and I'm not sure all the members are convinced that the details of the proposal are exactly how we'd like them to be.

Your alternative remains to pursue this issue:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/963

But my sense is that this is suck and will not become unstuck easily.  I'm not sure I can make it become unstuck on my own.  I'd like to see how the discussion unfolds for the IDE WG because that looks like a path of least resistance.

**Comment by merks** [comment]
> > Note too that neither the WG nor I make any of the rules, the Foundation makes the rules and we are all bound by them
> 
> So there is a rule against our will to have project page listing some possible committers to sponsor? Where can we such rule explicitly? Was is discussed in some Board meeting? Which meeting minutes should we read to learn more about that? What bugs me the most is that so far, we've not gotten any argument _against_ doing that from anyone at EMO; we've just got it enabled, and then disabled without a clear reason and then silence despite numerous pings. And without a clear reason for EF to disable it, then it leaves room for the worst interpretations about EF priorities.

I'm not sure where the rules are written explicitly if anywhere.  I don't recall any board discussion about such rules so I'm pretty sure there weren't any.  The Foundation staff is empowered to make policies that are not reviewed in detail by the Board.  I understand and share your frustrations. 

I don't believe there is any rule that prevents you from adding arbitrary links from the non-existent readme of the eclipse-tycho organization:

https://github.com/eclipse-tycho/

Have you considered that?

**Comment by akurtakov** [comment]
I start with https://github.com/eclipse-tycho/tycho/pull/1350 doing that.

**Comment by jonahgraham** [comment]
This comment section is long and I only skim read it. I don't speak for the IDE WG Steering Committee - but I am a member of it (as chair of the Planning Council). Tycho is not in any way bound by anything the IDE WG does! Nor should it be. The IDE WG is trying to make things better and coordinate some activities related to the Eclipse IDE releases. 

Whether a project can have sponsorship, or encourage sponsoring of its committers is well [outside the scope](https://www.eclipse.org/org/workinggroups/eclipse-ide-charter.php) of the WG. 

Personally I don't see anything at all wrong with what @mickaelistria showed as an example in https://github.com/mickaelistria/tycho - and other projects at the EF do this today (maybe they aren't allowed to and "just did it"). Also, for example, [CDT has long had a list of contractors](https://wiki.eclipse.org/CDT:Services) you can hire to enhance CDT, not exactly the same as sponsorship, but similar.

As @merks mentioned the EF is looking at sponsorship and using Adoptium as a pilot. I hope the EF can give more clarity soon to their plans in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/963 (Which I also skimmed through but may have missed stuff).

**Comment by martinlippert** [comment]
Why not give people choice here? It seems to me like this discussion is not necessarily an either-or. What about enabling GitHub Sponsorship and then let sponsors decide themselves whether they want to sponsor an individual or put their money into the hands of the WG to pool money and then sponsor larger efforts / dev work? Both seems to be a totally reasonable and valuable thing to do and I see no reason why either of those two options would not be "allowed".

**Pull request merged**
