### PR TITLE
Allow building on custom MANIFEST, feature, category and product files

### LINKED ISSUE #1621: Do not overwrite MANIFEST.MF and feature.xml files during packaging
Currently, I'm trying to implement multi-branding for an application.
This means I process resources via filtering, `MANIFEST.MF` and `feature.xml` files too to rename bundle symbolic names at build time.

The Tycho Packaging Plugin however always overwrite those two files when packaging the product, even if they're already present under `${project.build.directory}`.

https://github.com/eclipse-tycho/tycho/blob/77243cebc93d0bdbaf31e0e1b1055e29182958d8/tycho-packaging-plugin/src/main/java/org/eclipse/tycho/packaging/PackagePluginMojo.java#L267-L269

And

https://github.com/eclipse-tycho/tycho/blob/77243cebc93d0bdbaf31e0e1b1055e29182958d8/tycho-packaging-plugin/src/main/java/org/eclipse/tycho/packaging/PackageFeatureMojo.java#L124-L130

The proposed change is checking for `!file.exists()` before writing.  
If it's ok I have a PR ready, as I haven't found any workaround.

### PR DESCRIPTION
**Pull request by lppedd**
Fixes #1621.  
Old - closed - PR targeting 2.7.5 is #1623.

Example coming soon.

### CODE REVIEW

**Comment by lppedd** [comment]
@laeubi I have updated the integration test. Let me know if it's sufficient or if I have to add something else.

**Comment by laeubi** [comment]
It seems some test are failing, can you have a look?

**Comment by lppedd** [comment]
@laeubi you mean these from Jenkins?
```
org.eclipse.tycho.buildnumber.test.PackageFeatureMojoTest.testAddMavenDescriptorSetToTrue
org.eclipse.tycho.buildnumber.test.PackageFeatureMojoTest.testAddMavenDescriptorNotAddedPerDefault
org.eclipse.tycho.buildnumber.test.PackageFeatureMojoTest.testLicenseFeature
```

**Comment by lppedd** [comment]
@laeubi not sure why, but parameters default values referring to interpolated project properties are `null`.
Shouldn't they be evaluated correctly?

image

**Comment by laeubi** [comment]
@lppedd if i rembmer correctly, you need to se then `required = true`

**Comment by lppedd** [comment]
@laeubi nope. I think it's a limitation of the testing harness.
`ObjectWithFieldsConverter` is used to inject values, so you'll get only stuff configured via XML.
Default values are not inject.

I suppose the tests-wide method `setVariableValueToObject` exists because of this problem?

**Comment by lppedd** [comment]
Yes I can confirm it's only in testing.

Testing uses `ResolverExpressionEvaluatorStub`
Maven uses `PluginParameterExpressionEvaluator`

**Comment by laeubi** [comment]
> I suppose the tests-wide method `setVariableValueToObject` exists because of this problem?

Thats possible, lets try if that helps.

**Comment by lppedd** [comment]
No failures! I'll push a cleanup commit and then I think I'm done here 😄

**Review by laeubi — APPROVED** [review]
Looks good.

**Comment by laeubi** [comment]
@lppedd can you rebase and squash the intermediate commits into one and adding a short description as the commit message?

**Comment by lppedd** [comment]
@laeubi done. I have kept the lifecycle change as a separate commit, as it is indeed a different concern. 
Can squash that too in case tho.

**Comment by lppedd** [comment]
@laeubi thank you!  
Could you remind me what's needed to ask for a backport to the current release 3.0.x?

**Comment by laeubi** [comment]
If you want to backport it, checkout the `tycho 3.x `branch. Check if the version is already increased (`3.1.0-SNAPSHOT` in this case) if not update version

`mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=<NEXT_VERSION>-SNAPSHOT`

then backport your desired change and open a PR against the tycho-3.x branch.

**Pull request merged**
