### PR TITLE
Fix some eclipse warnings

### PR DESCRIPTION
**Pull request by Bananeweizen**
No functional changes, rather just going after different warnings sorted by type.

### CODE REVIEW

**Comment by laeubi** [comment]
@Bananeweizen it seems this breaks something do you like to take a look? or probably trying some smaller batches?

**Comment by Bananeweizen** [comment]
removed the try-with-resource refactoring, as it seems to have changed some logic in the exception handling there.

**Comment by akurtakov** [comment]
I feel better about the future of a project when I see such changes compared to trying to get a new feature in quick and dirty way :)

**Comment by laeubi** [comment]
Thanks @Bananeweizen for helping cleaning things up with Tycho codebase!

**Pull request merged**
