### PR TITLE
Issue 1943 reproducer

### PR DESCRIPTION
**Pull request by glatuske**
Fix for #1943

I have cherry-picked the missing change, decremented Tycho version for view modules and added a test case to existing JUnit 5.9 integration tests for the non working parametrized tests with method source.

### CODE REVIEW

**Comment by laeubi** [comment]
@mickaelistria as you did the inital implementation, can you review this backport?

**Comment by laeubi** [comment]
@glatuske I think you need to cherry-pick the commit e1d2c8b392f3697b8230a178713a083a3bbfe99b first.

**Comment by laeubi** [comment]
And if the test for junit is new, it would be good to first integrate this test into the master branch!

**Comment by glatuske** [comment]
> And if the test for junit is new, it would be good to first integrate this test into the master branch!

I have created another PR for the cherry-pick: https://github.com/eclipse-tycho/tycho/pull/1974

**Comment by laeubi** [comment]
> > @glatuske I think you need to cherry-pick the commit [e1d2c8b](https://github.com/eclipse-tycho/tycho/commit/e1d2c8b392f3697b8230a178713a083a3bbfe99b) first.
> 
> @laeubi I have cherry-picked the commit as well.

In the meanwhile I already included a fix for this, so a rebase would be only required then.

**Comment by laeubi** [comment]
Thanks for backporting this

**Pull request merged**
