### PR TITLE
issue/1235 initial attempt at recalculating start plugins

### PR DESCRIPTION
**Pull request by tolland**

### CODE REVIEW

**Comment by tolland** [comment]
Hmm, it's still saying `Product example.product could not be found.` :

```
!ENTRY org.eclipse.equinox.app 0 0 2022-08-03 21:42:12.267
!MESSAGE Product example.product could not be found.
!SESSION 2022-08-03 22:01:46.335 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.15
java.vendor=Red Hat, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.equinox.app 0 0 2022-08-03 22:01:47.142
!MESSAGE Product example.product could not be found.
!SESSION 2022-08-03 22:06:32.100 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.15
java.vendor=Red Hat, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.equinox.app 0 0 2022-08-03 22:06:32.808
!MESSAGE Product example.product could not be found.
```

**Comment by laeubi** [comment]
@tolland do you plan working on this?

**Comment by tolland** [comment]
I do think that its useful to have this working... I got stuck here:



Though I've definitely completed the contributor agreement:



and the email addresses match between github and eclipse foundation. But it says no:

**Comment by laeubi** [comment]
@tolland I triggered a re-validation, if this do not work, please make sure you have entered your github username in your eclipse profile under the "social links" section.

**Comment by cdietrich** [comment]
Maybe a bug in the tooling? In the error message the uk from the mail seems to be gone

**Pull request closed without merging**
