### PR TITLE
Also consider profile properties when looking for disable mirror keys

### PR DESCRIPTION
**Pull request by laeubi**
I also created
- https://github.com/eclipse-equinox/p2/pull/431

as currently Tycho does ignore any mirrors (by modify the repository under the hood), but the mirror list is still loaded in such a case!

Replaces:
- https://github.com/eclipse-tycho/tycho/pull/3378

### CODE REVIEW

**Comment by laeubi** [comment]
@vogella @Phillipus please validate

**Comment by Phillipus** [comment]
@laeubi I've tested this with both options `tycho.disableP2Mirrors` and `eclipse.p2.mirrors` in my `settings.xml` file and profile and it is working as expected.

Thanks for this, sorry I didn't take it further in the original PR, your implementation is much better than what I would have done!

**Comment by laeubi** [comment]
Backported here:
- https://github.com/eclipse-tycho/tycho/pull/3387

**Comment by vogella** [comment]
Thanks @laeubi for fixing it and @Phillipus for identifying the issue and helping with testing it.

You guys are cool.

**Pull request merged**
