### PR TITLE
No digest algorithm

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by laeubi** [comment]
At thir point of time we only generate inital metadata (what fails in earlier stages as OSGi is not ready there), the error message is ommited for the final produced artifact (that is attatch-p2-metadata).

**Comment by laeubi** [comment]
I'm a bit confused as you linked 
- https://github.com/eclipse-tycho/tycho/issues/1482
what is much older as the mentioned commit, so can you explain what exactly message you can reproduce/causes issues in the test case I then can take a look at this.

**Comment by mickaelistria** [comment]
Ineed, my analysis was incomplete. I found 1 commit that added the NO_MD5 option (which is poorly named as it's "no signature"). But there are other and older places where this is set too which are more involved in the issue.

**Comment by laeubi** [comment]
I'll try to take a look at the "No signature available" stuff, so I assume the new test-case shows this message already?

**Comment by mickaelistria** [comment]
> I'll try to take a look at the "No signature available" stuff, so I assume the new test-case shows this message already?

Yes.
Note that https://github.com/eclipse-tycho/tycho/commit/231d495aeccf88586faf6e9d9b16c5d2e1ff3933 was a decent functional fix, making the test pass successfully (not showing the message); I am just trying to find something better if possible.

**Comment by laeubi** [comment]
I have a fix for this locally that do work with standard P2 (so no extra work by Tycho) i'll push this tomorrow after enhancing my testcase a bit ...

**Comment by laeubi** [comment]
See:
- https://github.com/eclipse-tycho/tycho/pull/2008

**Comment by laeubi** [comment]
I think this one is not required anymore?

**Comment by mickaelistria** [comment]
> I think this one is not required anymore?


Indeed

**Pull request closed without merging**
