### PR TITLE
Allow configuration of packaging types

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by akurtakov** [comment]
How these license reviews popped up for this patch? I'm totally puzzled.

**Comment by laeubi** [comment]
No idea, but it is not related to this PR I think but either a bug in the License check or some dependency magically updates because of 
- https://github.com/eclipse-platform/eclipse.platform.releng/issues/119

**Comment by laeubi** [comment]
Replaced by:
- https://github.com/eclipse-tycho/tycho/pull/1942

**Pull request closed without merging**
