### PR TITLE
Reproducer for the .settings folder of a project is not considdered if it is a linked resource

### PR DESCRIPTION
**Pull request by sthdev**
This integration test tests if tycho follows project settings if the `.settings` folder of a project is a linked resource, which refers to another folder.

### CODE REVIEW

**Comment by laeubi** [comment]
@sthdev can you please make sure to sign the ECA?

**Comment by sthdev** [comment]
I did but there is no connection between my eclipse and my GitHub account. How would I do this?

**Comment by laeubi** [comment]
> I did but there is no connection between my eclipse and my GitHub account. How would I do this?

In your eclipse profile you can add the github user name, you must also make sure that the mail of the commit is the one you signed the ECA with.

**Comment by sthdev** [comment]
Well, that's a problem. I did not sign the commits and I used a fake git user for technical reasons. I'll have to recommit the changes but I will not get around to do it before next week.

**Comment by sthdev** [comment]
The commit email matches the ECA mail, now.

**Comment by laeubi** [comment]
@sthdev it seems the test does not fail, can you check why it does not gives a failing test? Maybe one can better use a warning in the code, the enable failOnWarning in the settings of tycho but suppress the warning in the project settings.

Thsi should then result in a failing compile if project settings are not considered.

**Comment by laeubi** [comment]
Closing as no feedback from original author. @sthdev if this is still interesting for you please let me know so we can reopen the PR.

**Pull request closed without merging**
