### PR TITLE
Update maven target locations

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov in the target file there is also the following TODO:

```
<!-- Currently still using Orbit variants instead of upstream one in Platform
				because Tycho 2.7.x which is used to build current Tycho 3.0.0-SNAPSHOT
doesn't support new/official JUnit bundles -->
```

as we are now using Tycho 3.0 should this location be updated/deleted/...?

**Comment by akurtakov** [comment]
> @akurtakov in the target file there is also the following TODO:
> 
> ```
> 
> ```
> 
> as we are now using Tycho 3.0 should this location be updated/deleted/...?

I think so. @mickaelistria did this work IIRC but good catch on yet another thing we would better get fixed.

**Comment by laeubi** [comment]
GH failures are not related...

**Comment by laeubi** [comment]
@mickaelistria do you like to create a follow-up regarding the junit bunldes updates?

**Pull request merged**
