### PR TITLE
Support key matching of PGP subkey bindings

### PR DESCRIPTION
**Pull request by merks**
Also provide logging of the keys being considered and ultimately used.

https://github.com/eclipse-tycho/tycho/issues/1728

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov

With these changes I expect the following to work on the ci.eclipse.org instance for any project with PGP keys enabled:
```
    stage('Build') {
      steps {
        withCredentials([
          file(credentialsId: 'secret-subkeys.asc', variable: 'KEYRING'),
          string(credentialsId: 'gpg-passphrase', variable: 'KEYRING_PASSPHRASE')]) {
          sh '''
            mvn \
              -Dtycho.pgp.signer="bc" \
              -Dtycho.pgp.signer.bc.secretKeys="${KEYRING}" \
              -Dgpg.passphrase="${KEYRING_PASSPHRASE}" \
              clean \
              verify
            '''
        }
      }
    }
```
I expect no need to specify the keyname; given there is only one signing key in the key ring, that one should be found.  Also, there is no need to initialize the gpg key ring because it's not used when `tycho.pgp.signer.bc.secretKeys` is specified.

I tested this on Oomph's ci instance:
```
java -jar bc.jar 2E8E9CF8 ${KEYRING_PASSPHRASE} ${KEYRING}
java -jar bc.jar ${KEYRING_PASSPHRASE} ${KEYRING}
```
Both successfully signed a file:
```
+ java -jar bc.jar 2E8E9CF8 **** ****
Secret key available for public key: 1e6f99794576b6032d257293c34aebd62e8e9cf8
Secret key available for public key: 4777dd30711ea6af367f3478eb3c38f6c7a0f00d
Trying to get the private key of the secret key of public key: 4777dd30711ea6af367f3478eb3c38f6c7a0f00d
Got the private key of the secret key of public key: 4777dd30711ea6af367f3478eb3c38f6c7a0f00d
+ java -jar bc.jar **** ****
Secret key available for public key: 1e6f99794576b6032d257293c34aebd62e8e9cf8
Secret key available for public key: 4777dd30711ea6af367f3478eb3c38f6c7a0f00d
Trying to get the private key of the secret key of public key: 4777dd30711ea6af367f3478eb3c38f6c7a0f00d
Got the private key of the secret key of public key: 4777dd30711ea6af367f3478eb3c38f6c7a0f00d
Finished: SUCCESS
```

**Comment by laeubi** [comment]
@merks the commit author looks strange.. also you probably like to include "Fixes #1731" in the commit message.

**Comment by merks** [comment]
@akurtakov  I think if you remove the `<keyname>` configurations from the two pom.xmls and specify `-Dgpg.keyname=99CAA96C` in the Jenkins file, i.e., the key ID of the **subkey**, along with the other stuff I showed in https://github.com/eclipse-tycho/tycho/pull/1731#issuecomment-1327520540 that it should work even before this PR's fix is in a build.   Remove also the gpg initialization stuff which is unneeded in this case.   That approach worked for me here:

https://ci.eclipse.org/oomph/job/jetty/job/jetty-mirror-4.0/

So you may wish to try that...

**Comment by merks** [comment]
> @merks the commit author looks strange.. also you probably like to include "Fixes #1728" in the commit message.

Oh yes, that launched ID  is in an environment where my local gpg stuff works.  Sorry, I'll fix the commit

**Comment by merks** [comment]
> you probably like to include "Fixes #1728" in the commit message.

Well, I'm not really sure this change can be said to actually fix that problem.  It just avoids that problem by not using gpg at all...

**Comment by merks** [comment]
@laeubi Sometimes I see stack traces like this in a build log, but it does break the build:
```
Caused by: org.eclipse.core.runtime.CoreException: Extension registry provider is already set.
    at org.eclipse.core.internal.registry.RegistryProviderFactory.setDefault (RegistryProviderFactory.java:34)
    at org.eclipse.core.internal.registry.osgi.Activator.startRegistry (Activator.java:148)
    at org.eclipse.core.internal.registry.osgi.Activator.start (Activator.java:60)
    at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run (BundleContextImpl.java:818)
    at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run (BundleContextImpl.java:1)
    at java.security.AccessController.doPrivileged (AccessController.java:569)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator (BundleContextImpl.java:810)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.start (BundleContextImpl.java:767)
    at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0 (EquinoxBundle.java:1032)
    at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker (EquinoxBundle.java:371)
    at org.eclipse.osgi.container.Module.doStart (Module.java:605)
    at org.eclipse.osgi.container.Module.start (Module.java:468)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run (ModuleContainer.java:1852)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute (EquinoxContainerAdaptor.java:136)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel (ModuleContainer.java:1845)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel (ModuleContainer.java:1788)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel (ModuleContainer.java:1750)
    at org.eclipse.osgi.container.SystemModule.startWorker (SystemModule.java:269)
    at org.eclipse.osgi.container.Module.doStart (Module.java:605)
    at org.eclipse.osgi.container.Module.start (Module.java:468)
    at org.eclipse.osgi.container.SystemModule.start (SystemModule.java:193)
    at org.eclipse.osgi.internal.framework.EquinoxBundle.start (EquinoxBundle.java:445)
    at org.eclipse.osgi.internal.framework.EquinoxBundle.start (EquinoxBundle.java:464)
    at org.eclipse.osgi.launch.Equinox.start (Equinox.java:139)
    at org.eclipse.sisu.osgi.connect.PlexusFrameworkConnectServiceFactory.getFramework (PlexusFrameworkConnectServiceFactory.java:145)
    at org.eclipse.sisu.osgi.connect.PlexusFrameworkConnectServiceFactory.locateClass (PlexusFrameworkConnectServiceFactory.java:359)
    at org.eclipse.sisu.osgi.connect.PlexusFrameworkConnectServiceFactory.getService (PlexusFrameworkConnectServiceFactory.java:343)
    at org.eclipse.tycho.p2maven.DefaultProvisioningAgent.getOSGiAgentService (DefaultProvisioningAgent.java:80)
    at org.eclipse.tycho.p2maven.DefaultProvisioningAgent.getService (DefaultProvisioningAgent.java:47)
    at org.eclipse.equinox.p2.core.IProvisioningAgent.getService (IProvisioningAgent.java:86)
    at org.eclipse.tycho.gpg.SignRepositoryArtifactsMojo.execute (SignRepositoryArtifactsMojo.java:179)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
```
Any ideas what might cause this and how to avoid it?

**Comment by laeubi** [comment]
It might be that your plugin (implicitly) creates a new EquinoxFramework, do you see this always in the builds or only sometimes / with some configurations.

**Comment by merks** [comment]
There's this:

https://github.com/eclipse-tycho/tycho/blob/dca0dc2fbc3ba349ad2fa627f4fd9fb1075cd206/tycho-gpg-plugin/src/main/java/org/eclipse/tycho/gpg/SignRepositoryArtifactsMojo.java#L150-L151

And that's used here:

https://github.com/eclipse-tycho/tycho/blob/dca0dc2fbc3ba349ad2fa627f4fd9fb1075cd206/tycho-gpg-plugin/src/main/java/org/eclipse/tycho/gpg/SignRepositoryArtifactsMojo.java#L173-L179

That's the stack trace.  We haven't used this long enough to know when this happens; I suspect it's after the other parts that assemble the repository.  I'm not sure how the infrastructure ensures that only one Equinox framework is created, which is why I ask...

**Comment by merks** [comment]
Maybe it specifically happens only after a mirror...
```
      <plugin>
        <groupId>org.eclipse.tycho.extras</groupId>
        <artifactId>tycho-p2-extras-plugin</artifactId>
        <version>${tycho-version}</version>
        <executions>
          <execution>
            <phase>generate-resources</phase>
            <goals>
              <goal>mirror</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <source>
            <repository>
              <id>jetty</id>
              <layout>p2</layout>
              <url>mvn:org.eclipse.jetty:jetty-p2:${jetty-version}:zip:p2site</url>
            </repository>
          </source>
          <compress>true</compress>
          <xzCompress>true</xzCompress>
          <keepNonXzIndexFiles>false</keepNonXzIndexFiles>
          <followStrictOnly>true</followStrictOnly>
        </configuration>
      </plugin>
```

**Comment by laeubi** [comment]
This is just a guess but instead of

```
 @Component(role = IProvisioningAgent.class) 
 private IProvisioningAgent agent;
```

You could use your already required:

```
  @Component(role = EquinoxServiceFactory.class, hint = "tycho-core")
   private EquinoxServiceFactory serviceFactory;
```

and do  `serviceFactory.getService(IProvisioningAgent.class)` here... maybe this helps.


>  I'm not sure how the infrastructure ensures that only one Equinox framework is created, 

There is no such guarantee and actually in a perfect OSGi world there would be no need for such requirement at all, but sadly  `platform/equinox` uses a lot of static singeltons that interfere here... I'm trying to mitigate this here and there but at the moment the best choice is to always use tycho-core as a base for the lookup because this is the only one guaranteed to only exits once.

**Comment by merks** [comment]
@laeubi Cool, I will give that a try.

**Comment by merks** [comment]
Yeah, the build passed. :-)

**Comment by laeubi** [comment]
Should this be merged or do you have additional things here to do?

**Comment by merks** [comment]
Please merge.   This will make what's described here work:

https://github.com/eclipse-tycho/tycho/pull/1731#issuecomment-1327520540

**Pull request merged**
