### PR TITLE
Fix spelling in tycho-ds and make message more clear

### PR DESCRIPTION
**Pull request by kysmith-csg**

### CODE REVIEW

**Comment by laeubi** [comment]
@merks @akurtakov @HannesWell what do you think? I'm not sure if the wording "new" is really appropriate here, generated code is usually always "new".

**Comment by HannesWell** [comment]
I agree, especially in the context of CI builds where the repo is usually clean in the beginning and the missing components are always generated. 

The word `existing` could also be `preexisting` or `already existing`. But just existing is also fine for me.

**Comment by merks** [comment]
Yes, `existing` is fine.

**Comment by kysmith-csg** [comment]
Thanks all for the feedback. Updated to remove "new".

**Review by laeubi — APPROVED** [review]
Looks fine to me

**Pull request merged**
