### PR TITLE
Use github action codeql

### PR DESCRIPTION
**Pull request by carstenartur**

### CODE REVIEW

**Comment by laeubi** [comment]
@carstenartur can you give some more details and possibly update the description of this PR e.g.:

- Have you already applied this config to your fork and checked that the codebase actually complies to codeql?
- What kind of bugs do you expect to be detect by this?
- Do we need to maintain any configuration beside the yml file or possibly other impacts?
-  maybe more for those not yet familiar with codeql

Beside this it might be good to squash your intermediate commits into one.

**Comment by carstenartur** [comment]
> @carstenartur can you give some more details and possibly update the description of this PR e.g.:
> 
> 
> 
> - Have you already applied this config to your fork and checked that the codebase actually complies to codeql?

I applied it and get some issues as you can see here

https://github.com/carstenartur/tycho/security/code-scanning?page=2


> 
> - What kind of bugs do you expect to be detect by this?
> 

See above

> - Do we need to maintain any configuration beside the yml file or possibly other impacts?

Basically no - but I wonder why it does not pick up the codeql execution in the pull requests build. I have no explanation right now for that. Maybe tycho makes use of a customized build that ignores additions to github actions??
> 
> -  maybe more for those not yet familiar with codeql
> 

Codeql supports a bunch of investigations in different files and is integrated for supporting pull requests and issue tracking.
> 
> 
> Beside this it might be good to squash your intermediate commits into one.

This is so far a test - althought I'm a bit lazy about that personally since I'm used to make use of the "sqeeze on merge" feature of github.

**Comment by laeubi** [comment]
> I applied it and get some issues as you can see here

It seems I can't access this page (most likely for security reasons)

 > See above

do you plan to work on such raised issues from codeql?

> but I wonder why it does not pick up the codeql execution in the pull requests build. I have no explanation right now for that. Maybe tycho makes use of a customized build that ignores additions to github actions??

Actions only run if they do not exits if you are the maintainer of that repository, so it will only run when merged the first time.

> Codeql supports a bunch of investigations in different files and is integrated for supporting pull requests and issue tracking.

Do you plan to support Tycho in this regard? I'm not sure if any of the current @eclipse-tycho/technology-tycho-committers  uses codeql or has experience with that.

> This is so far a test - althought I'm a bit lazy about that personally since I'm used to make use of the "sqeeze on merge" feature of github.

I think in this case one clean commit with a descriptive commit message would be more appropriate.

**Comment by carstenartur** [comment]
> > I applied it and get some issues as you can see here
> 
> 
> 
> It seems I can't access this page (most likely for security reasons)

That can be as this list security issues too.
> 
> 
> 
>  > See above
> 
> 
> 
> do you plan to work on such raised issues from codeql?

I worked on similar issues in the past but I see the most important point in preventing new additions of code with issues.

> 
> 
> 
> > but I wonder why it does not pick up the codeql execution in the pull requests build. I have no explanation right now for that. Maybe tycho makes use of a customized build that ignores additions to github actions??
> 
> 
> 
> Actions only run if they do not exits if you are the maintainer of that repository, so it will only run when merged the first time.

Ah, ok. For my repositories they always ran as part of the pull request. So that is why😀
> 
> 
> 
> > Codeql supports a bunch of investigations in different files and is integrated for supporting pull requests and issue tracking.
> 
> 
> 
> Do you plan to support Tycho in this regard? I'm not sure if any of the current @eclipse-tycho/technology-tycho-committers  uses codeql or has experience with that.

Because of the integration of codeql you can mark issues as ignored. That way you can live with issues (eg in test code) without sacrifying protection against introduction of new bugs.
So I think it should not put more load on tycho maintainers.
> 
> 
> 
> > This is so far a test - althought I'm a bit lazy about that personally since I'm used to make use of the "sqeeze on merge" feature of github.
> 
> 
> 
> I think in this case one clean commit with a descriptive commit message would be more appropriate.

Of course..

**Comment by carstenartur** [comment]
Which licenses have to be vetted? This change does not introduce new dependencies to tycho.

**Comment by Bananeweizen** [comment]
```
 [INFO] License information could not be automatically verified for the following content:
[INFO] 
[INFO] maven/mavencentral/org.apache.maven.plugins/maven-failsafe-plugin/3.0.0-M5
```
I'm not sure about how to whitelist a license, but the other committers should be able to help.

**Comment by akurtakov** [comment]
What is the status of this one?

**Comment by carstenartur** [comment]
There are concerns regarding the question how fast issues showing up because of this github action get fixed. As I can't make promises currently maybe close it for the moment?

**Comment by akurtakov** [comment]
Ok, closing for now. If/when you have time don't hesitate to open a new one.

**Pull request closed without merging**
