### PR TITLE
Resolve target definition variables during p2 repository assembly

### PR DESCRIPTION
**Pull request by kysmith-csg**
Recreation of #3042 to account for new base branch (master vs v4.0.x).

### CODE REVIEW

**Review by HannesWell — APPROVED** [review]
Perfect.
Thank you.

**Comment by HannesWell** [comment]
> ## 💔 All backports failed
> Status 	Branch 	Result
> ❌ 	tycho-4.0.x 	Backport failed because of merge conflicts

OK, looks like this was a bad example to demonstrate the automated back-port feature. :/

Can you just re-open https://github.com/eclipse-tycho/tycho/pull/3042 to handle the 'back-porting'?

**Comment by kysmith-csg** [comment]
@HannesWell I am not able to reopen pull requests so I've opened #3051.

**Comment by HannesWell** [comment]
> @HannesWell I am not able to reopen pull requests so I've opened #3051.

Thanks.
From my experience one can only reopen a closed PR if the branch still exists and points to the exact commit it pointed last when the PR was closed. But additionally this might also require commiter rights (I'm not sure about that).

**Pull request merged**
