### PR TITLE
Adjust code for Tycho to run on maven 3.9.0 and use it for GH Actions

### PR DESCRIPTION
**Pull request by laeubi**
Fix 
- https://github.com/eclipse-tycho/tycho/issues/1557
- https://github.com/eclipse-tycho/tycho/issues/1148

### CODE REVIEW

**Comment by laeubi** [comment]
FYI @akurtakov with this Tycho should work on maven 3.8.x and maven 3.9.x

- GH Action uses maven 3.9.x
- Jenkins uses maven 3.8.x

**Comment by lppedd** [comment]
What's the Tycho link with takari-polyglot? Curious to know why Tycho is using it.

**Comment by laeubi** [comment]
takari-polyglot is what tycho pomless extends.

**Comment by akurtakov** [comment]
Thanks @laeubi ! Any reason to not merge it ?

**Pull request merged**
