### PR TITLE
Update Releasing with a note to sponsored items

### PR DESCRIPTION
**Pull request by laeubi**
@mickaelistria @akurtakov what do you think as project lead?

Beside that, I think we can move the file to the root and name it RELEASING.MD

### CODE REVIEW

**Review by akurtakov — COMMENTED** [review]
I don't mind it in general. Only comment is about "special" thanks as that way it sounds to me like we thank people paying more than these contributing patches and I would like these to sound equally important.

**Comment by laeubi** [comment]
@akurtakov I'm not a native speaker so its often hard to guess how it "sounds", can you maybe suggest a better wording? Maybe "we would like to also thank [...] for sponsoring contributions"?

**Comment by akurtakov** [comment]
> @akurtakov I'm not a native speaker so its often hard to guess how it "sounds", can you maybe suggest a better wording? Maybe "we would like to also thank [...] for sponsoring contributions"?

I really like ^^^, go with it.
 Btw, I'm not native speaker too and probably majority of people that will read it and everyone will read it with his own mindset like I did.

**Comment by mickaelistria** [comment]
I read it same way as @akurtakov and prefer the suggested rephrasing which is perfect and welcome.

**Comment by laeubi** [comment]
I have updated the text, please leave an approval or suggest changes :-)

**Review by mickaelistria — APPROVED** [review]

**Review by akurtakov — APPROVED** [review]

**Comment by laeubi** [comment]
What do you think about moving/renaming that file? I'll then open another PR for this...

**Comment by mickaelistria** [comment]
> What do you think about moving/renaming that file?

I personally don't care as long as payload remains relatively easy to find (and in the Git repo).

**Pull request merged**
