### PR TITLE
Make Tycho SBOM mapper configurable w.r.t. the project packaging types

### PR DESCRIPTION
**Pull request by ptziegler**
Instead of being applied on all packaging types (even those where it
doesn't make sense like the target platform), the user is now able to
configure for which project types the Tycho model converter is used.

By default (if nothing else is specified), this converter is only used
for plugins and features, to avoid issues when the e.g. the target
definition is defined in its own module or the the reactor contains
non-Tycho packaging types (jar/pom/bundle/...).

### CODE REVIEW

**Comment by ptziegler** [comment]
The test will likely fail because the current implementation can't handle multiple test fragments. But this should be fixed with https://github.com/eclipse-tycho/tycho/pull/3913.

**Comment by laeubi** [comment]
@ptziegler do you plan to finish this one? There could probably be a new release coming at the end of the Platform release cycle.

**Comment by ptziegler** [comment]
The tests work locally, let's hope Jenkins agrees as well.

**Comment by ptziegler** [comment]
Hm... of course that's the problem; The log file is simply getting too big.
Because the test is executed on `debug` level, everything that is logged by CycloneDX will show up in the error log. And this is just too much for the test suite to handle.

**Comment by ptziegler** [comment]
A log file with size 6.1GB... dear lord.

**Comment by merks** [comment]
It’s probably rife with important and relevant details that you will wish to peruse carefully and fully.

**Comment by ptziegler** [comment]
The remaining test failure seems unrelated. To keep things simple, I've removed the debug flag for the SBOM tests, which should drastically reduce the size of the build log.

**Comment by laeubi** [comment]
@ptziegler should this be backported to Tycho 4 branch? If yes please add the label to PR. I have now rebased and enabled automerge.

**Comment by ptziegler** [comment]
@laeubi 

If would be great if this could be back-ported, just to have a consistent behavior accross the board. But I fear I don't have permission to add any labels to this PR.
image

**Pull request merged**
