### PR TITLE
Add Java 17 hint to Migration Guide

### PR DESCRIPTION
**Pull request by phermsdorf**

### CODE REVIEW

**Comment by laeubi** [comment]
@phermsdorf can you rebase your branch on [tycho-3.0.x](https://github.com/eclipse-tycho/tycho/tree/tycho-3.0.x)?

**Comment by phermsdorf** [comment]
@laeubi i just realized i only got the master branch in my fork. How to rebase on the [tycho-3.0.x](https://github.com/eclipse-tycho/tycho/tree/tycho-3.0.x) branch? 

Sorry for the hassle ...

**Comment by laeubi** [comment]
No problem, does this helps? https://stackoverflow.com/questions/1783405/how-do-i-check-out-a-remote-git-branch

**Comment by laeubi** [comment]
Beside that I think you can go here: https://github.com/eclipse-tycho/tycho/blob/tycho-3.0.x/RELEASE_NOTES.md and hit the edit button (the one with a pencil)

**Comment by mickaelistria** [comment]
IMO, it's OK to merge it to master branch, as people who're going to read release notes are more likely to read them from the default branch shown on GitHub (master here)

**Comment by phermsdorf** [comment]
i tried again with #1403

**Comment by laeubi** [comment]
> IMO, it's OK to merge it to master branch, as people who're going to read release notes are more likely to read them from the default branch shown on GitHub (master here)

I usually collect all releasenote changes on the release branch and then sync with the master branch once the release  is out so we do not get too much noise.

As we always link the branch in the release doc these should be up-to-date first.

**Comment by akurtakov** [comment]
@phermsdorf Thanks for doing it! I had it in my list to do tomorrow as today was supposed to be day off.

**Comment by mickaelistria** [comment]
> I usually collect all releasenote changes on the release branch

For many projects, there is no such release branch, the release is a tag (immutable), so the release notes cannot easily be improved after the fact. On the other hand, maintaining them only the master branches allows to update them at any time, even after release.

**Comment by laeubi** [comment]
We can name it "version branch" if you think that makes a difference... nerveless the idea is that we can work on master branch without taking care of the release quiet/bugfix period. having diverging release notes on different branches and trying to not breaking references for older releases do not sounds valuable here nor I see any drawback with that..

**Comment by mickaelistria** [comment]
This change will be backported to master, right?

**Comment by laeubi** [comment]
If you think it is that important you can backport it now, otherwhise I would jsut wait for other feedback and submit all release note next week togehter with the update of the build tycho version.

**Pull request closed without merging**
