### PR TITLE
Normalize the host bundle symbolic name

### LINKED ISSUE #1769: Test plugin JAR generation creates invalid Bundle-SymbolicName
Method call [`TychoIntegrationTestMojo#createTestPluginJar`](https://github.com/eclipse-tycho/tycho/blob/1e3c6cd22154bb3499528cf2b88d2aef1ed79b05/tycho-surefire/tycho-surefire-plugin/src/main/java/org/eclipse/tycho/surefire/TychoIntegrationTestMojo.java#L208).

image

The resulting `Bundle-SymbolicName` is `com.ibm.pdtools.common.component.core;singleton:=true.90fd8144-0691-4773-a78b-00a93545e4f6`, which seems to be wrong.

If you confirm this indeed looks wrong I can submit a PR.

### PR DESCRIPTION
**Pull request by lppedd**
Fix #1769.

The first commit does the real thing.  
The second commit reformats the entire source file.

Kept them separate to ease reviewing.

### CODE REVIEW

**Comment by laeubi** [comment]
@lppedd what Eclipse formatter profile do you use for this reformating? I just tried to reformat the code from within my Eclipse but don't get the any changes here..

**Comment by lppedd** [comment]
@laeubi I actually use IntelliJ. The formatting profile is basically "adapt to what you find" (e.g. 4 spaces indentation).
Formatting of chained calls has been done manually.

**Comment by laeubi** [comment]
If the reformating is not essential I think it would be better to just fix the bug as this otherwise causes to much noise with different formatters and manual formatting in conjunction.

**Comment by lppedd** [comment]
@laeubi I can format it with the Eclipse formatter settings (`org.eclipse.jdt.core.prefs`), not an issue if you say it's ok.

**Comment by lppedd** [comment]
@laeubi reformatted again using the Eclipse formatter settings for the project (`tycho-surefire-plugin/.settings/org.eclipse.jdt.core.prefs`).

**Comment by lppedd** [comment]
@laeubi btw, would be cool to have a unified formatter (.xml, .epf) valid for the entire workspace. I could then simply import that formatter and work like if I was in Eclipse.

**Pull request merged**
