### PR TITLE
remove target platform from Tycho setup

### PR DESCRIPTION
**Pull request by Bananeweizen**
There is no PDE and target anymore.

### CODE REVIEW

**Comment by akurtakov** [comment]
@laeubi @merks Can you pleaase push this one if the change is fine? It's not needed but I'm not sure of Oomph mechanics.

**Comment by Bananeweizen** [comment]
@akurtakov The change is not urgent. The "Set target platform action" will just silently fail since a target with that name is not available. So no need to push this in a hurry, the Oomph setup is not broken.

**Comment by akurtakov** [comment]
Let's merge it. I trust you :) .

**Comment by laeubi** [comment]
> Let's merge it. I trust you :) .

Yes thats fine, thanks @akurtakov for taking care, I forgott that when dleting the target file with recent commit.

**Pull request merged**
